apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "keptn web service delivery"
spec:
  stages:
  - name: production
    sequences:
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed